out_dir: results
metric_best: auc
wandb:
  use: True
  project: molhiv
  entity: yd-research
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17) #range(1,21)
  model: Linear
  dim_pe: 16 #28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: sw_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 50
  residual: True
  # mlp_graph head configs
  act: gelu
  dropout: 0.05
  # fsw_gnn configs
  # fsw_embed_dim: None
  learnable_embedding: True
  concat_self: True
  bias: True
  conv_mlp_layers: 2
  conv_mlp_hidden_dim: None
  batchnorm_final: True
  batchnorm_hidden: True
  dropout_final: 0.05
  dropout_hidden: 0.05
  self_loop_weight: 1.0
  # edgefeat_dim: 0
  # encode_vertex_degrees: True
  #vertex_degree_encoding_function: 'identity'
  homog_degree_encoding: False
  vertex_degree_pad_thresh: 0.1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5