out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: Bond
  edge_encoder_bn: False
  max_neighbors: 5
  max_nodes: 444
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: sw_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3
  dim_inner: 134
  act: relu           
  residual: True                
  dropout: 0.0        
  sw_embed_dim: None
  learnable_embedding: False
  concat_self: True
  bias: True
  conv_mlp_layers: 2
  conv_mlp_hidden_dim: None
  batchnorm_final: True
  batchnorm_hidden: True
  dropout_final: 0.05
  dropout_hidden: 0.05
  self_loop_weight: 0.0 # Check 0.2
  vertex_degree_pad_thresh: 0.1
  homog_degree_encoding: False
optim:
  clip_grad_norm: False
  optimizer: adamW                        
  weight_decay: 0.0
  base_lr: 0.001 
  max_epoch: 190
  scheduler: reduce_on_plateau
  num_warmup_epochs: 0
  steps: None