out_dir: results
metric_best: ap
wandb:
  use: True
  project: peptides-func
  entity: yd-research
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: Bond
  edge_encoder_bn: False
  max_neighbors: 5
  max_nodes: 444
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: sw_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 3
  dim_inner: 120
  residual: True
  # mlp_graph head configs
  act: gelu
  dropout: 0.1
  # sw_gnn configs
  sw_embed_dim: None
  learnable_embedding: True
  concat_self: True
  bias: True
  conv_mlp_layers: 2
  conv_mlp_hidden_dim: None
  batchnorm_final: True
  batchnorm_hidden: True
  dropout_final: 0.1
  dropout_hidden: 0.1
  self_loop_weight: 0.5
  vertex_degree_pad_thresh: 0.1
  homog_degree_encoding: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.005
  base_lr: 0.005
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5